name       : usb-modeswitch
version    : 2.2.5
release    : 1
source     :
    - http://www.draisberghof.de/usb_modeswitch/usb-modeswitch-2.2.5.tar.bz2 : 8b2340303732aabc8c8e1cdd7d4352f61dcb942839f58ce22ba0ecfa122426d5
license    : GPL-2.0
summary    : USB ModeSwitch
description: |
    USB ModeSwitch is a mode switching tool for controlling USB devices with multiple "modes".
build      : |
    %make
install    : |
    %make_install
