name       : usb-modeswitch
version    : 2.6.0
release    : 4
source     :
    - https://www.draisberghof.de/usb_modeswitch/usb-modeswitch-2.6.0.tar.bz2 : c215236e6bada6e659fc195a31d611ea298a4bdb4d57a0d68c553b56585f8ba3
    - https://www.draisberghof.de/usb_modeswitch/usb-modeswitch-data-20191128.tar.bz2 : 3f039b60791c21c7cb15c7986cac89650f076dc274798fa242231b910785eaf9
license    : GPL-2.0-or-later
component  : network.util
summary    : Switch between USB modes
description: |
    USB ModeSwitch is a mode switching tool for controlling USB devices with multiple "modes".
builddeps  :
    - pkgconfig(libusb-1.0)
rundeps    :
    - tcl
setup      : |
    tar xf $sources/usb-modeswitch-data-*.tar.bz2
build      : |
    %make
install    : |
    install -dm00755 $installdir/%libdir%/systemd/system
    %make_install UDEVDIR=$installdir/%libdir%/udev SYSDIR=$installdir/%libdir%/systemd/system
    %make_install -C usb-modeswitch-data-* RULESDIR=$installdir/%libdir%/udev/rules.d
    cd $installdir
    rmdir -p var/lib/usb_modeswitch
