name       : usb-modeswitch
version    : 2.5.0
release    : 2
source     :
    - http://www.draisberghof.de/usb_modeswitch/usb-modeswitch-2.5.0.tar.bz2 : 31c0be280d49a99ec3dc0be3325bef320d9c04b50714ef0ce1e36a614d687633
    - http://www.draisberghof.de/usb_modeswitch/usb-modeswitch-data-20170205.tar.bz2 : e2dcfd9d28928d8d8f03381571a23442b3c50d48d343bc40a1a07d01662738d1
license    : GPL-2.0
component  : network.util
summary    : USB ModeSwitch
description: |
    USB ModeSwitch is a mode switching tool for controlling USB devices with multiple "modes".
builddeps  :
    - pkgconfig(libusb-1.0)
setup      : |
    tar xf $sources/usb-modeswitch-data-20170205.tar.bz2
build      : |
    %make
install    : |
    # Only installs systemd service if dir exists
    install -d $installdir/%libdir%/systemd/system
    %make_install UDEVDIR=$installdir/%libdir%/udev \
                  SYSDIR=$installdir/%libdir%/systemd/system
    pushd usb-modeswitch-data-*
        %make_install RULESDIR=$installdir/%libdir%/udev/rules.d
    popd
    # Empty dir
    rm -rf $installdir/var
