name       : usb-modeswitch
version    : 2.5.2
release    : 3
source     :
    - http://www.draisberghof.de/usb_modeswitch/usb-modeswitch-2.5.2.tar.bz2 : abffac09c87eacd78e101545967dc25af7e989745b4276756d45dbf4008a2ea6
    - http://www.draisberghof.de/usb_modeswitch/usb-modeswitch-data-20170806.tar.bz2 : ce413ef2a50e648e9c81bc3ea6110e7324a8bf981034fc9ec4467d3562563c2c
license    : GPL-2.0
component  : network.util
summary    : USB ModeSwitch
description: |
    USB ModeSwitch is a mode switching tool for controlling USB devices with multiple "modes".
builddeps  :
    - pkgconfig(libusb-1.0)
    - pkgconfig(tcl)
setup      : |
    tar xf $sources/usb-modeswitch-data-????????.tar.bz2
build      : |
    %make
install    : |
    # Only installs systemd service if dir exists
    install -d $installdir/%libdir%/systemd/system
    %make_install UDEVDIR=$installdir/%libdir%/udev \
                  SYSDIR=$installdir/%libdir%/systemd/system
    pushd usb-modeswitch-data-*
        %make_install RULESDIR=$installdir/%libdir%/udev/rules.d
    popd
    # Empty dir
    rm -rf $installdir/var
